controller:
  ingressClassResource:
    default: true
  service:
    type: LoadBalancer      # no k3s o servicelb expõe 80/443 nos IPs dos nodes
  metrics:
    enabled: true
  allowSnippetAnnotations: false
